version: '3.4'

services:
  emailservice.web:
    container_name: emailservice.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2000:80"
    networks:
      - my-proxy-net

networks:
    my-proxy-net:
      external:
        name: custom_network